config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'tasks#index'
  resources :goals
  resources :articles
  resources :tasks do
    collection do
      get 'search'
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  with_options numericality: { other_than: 1, message: "can't be blank" } do
    validates :mobile_id
  end

  validates :title, presence: true
  validates :content, presence: true
  validates :mobile_id, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  belongs_to :user
  has_one_attached :image
  has_many :task_tag_relations, dependent: :destroy
  has_many :tags, through: :task_tag_relations, dependent: :destroy

  def self.search(search)
    if search != ""
      Task.where('title LIKE(?)', "%#{search}%")
    else
      Task.all
    end
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :mobile
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :show, :destroy]
  
  def index
    @tasks = Task.all
    @goals = Goal.all
  end

  def new
    @task =Task.new
  end

  def show
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to root_path
    else
      @tasks = Task.all
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  def search
    if params[:keyword].present?
      @tasks = Task.search(params[:keyword])
    else
      redirect_to root_path
    end
  end


  private
  def task_params
    params.require(:task).permit(:title, :content, :start_time, :end_time, :mobile_id, :image, tag_ids: []).merge(user_id: current_user.id)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_calendar.erb
<div class="col-md-8">
  <%= month_calendar events: @tasks do |date, tasks| %>
    <%= date.day %>

    <% tasks.each do |task| %>
      <div>
        <%= link_to "#{Mobile.find_by(id: task.mobile_id)&.Mobile}", task, style: "text-decoration: none; font-size: small; color: black;" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<div class="form-wrapper">
  <%= form_with(model: @task, local: true, class: "form__wrapper") do |f| %>
    <div class="form-main">
      <div class="field">
        <%= f.label :title, "キャンペーン名", class: "form__label" %><br />
        <%= f.text_field :title, id: "title", class: "form__input" %>
      </div>
      <div class="field">
        <%= f.label :content, "キャンペーン内容", class: "form__label" %><br />
        <%= f.text_area :content, class: "form__textarea" %>
      </div>
      <div class="field">
        <%= f.label :start_time, "キャンペーン開始日", class: "form__label" %><br />
        <%= f.date_select :start_time, class: "form__select" %>
      </div>
      <div class="field">
        <%= f.label :end_time, "キャンペーン終了日", class: "form__label" %><br />
        <%= f.date_select :end_time, class: "form__select" %>
      </div>
      <div class="field">
        <%= f.label :mobile_id, "スマホキャリア", class: "form__label" %><br />
        <%= f.collection_select(:mobile_id, Mobile.all, :id, :Mobile, {class: "form-select form-control"}) %>
      </div>
      <!-- 以下を追記 -->
      <div class='form-group'>
        <%= f.label :mobile_id, "スマホブランド", class: "form__label" %><br />
        <%= f.collection_select(:tag_ids, Tag.all, :id, :tag_name) do |tag| %>
          <div class='form-check'>
            <%= tag.label class: 'form-check-label' do %>
              <%= tag.check_box class: 'form-check-input' %>
              <%= tag.text %>
            <% end %>
          </div>
        <% end %>
      </div>
    <!-- ここまで -->
    <div class="field">
        <%= f.label :image, "キャンペーンの画像", class: "form__label" %><br />
        <%= f.file_field :image, id: "task_image", class: "form__input" %>
      </div>
      <div class="actions">
          <%= f.submit "SEND", class: "form__btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/_goals-form.erb
<form id="goals-form">
  <table id="goals-table">
    <thead>
      <tr>
        <th>項目</th>
        <th>目標数</th>
        <th>獲得数</th>
        <th>達成率</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><input type="text" name="goal_name[]" /></td>
        <td><input type="number" name="goal_number[]" /></td>
        <td><input type="number" name="achievement_number[]" /></td>
        <td><span class="achievement-rate">0%</span></td>
      </tr>
    </tbody>
  </table>
  <button type="button" id="add-goal">項目を追加</button>
  <button type="submit" id="add-storage">保存</button>
</form>

app/views/tasks/_task.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= task.title %>
      </p>
      <%# 投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <div class="prototype__manage">
          <% if user_signed_in? && current_user.id == task.user_id %>
            <%= link_to "編集する", edit_task_path(task), method: :get, class: :prototype__btn %>
            <%= link_to "削除する", task_path(task), method: :delete, class: :prototype__btn %>
          <% end %>
            <%= link_to '戻る', root_path, class: :prototype__btn %>
        </div>
      <%# // 投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
      
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャンペーン内容</p>
          <p class="detail__message">
            <%= task.content %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">携帯キャリア</p>
          <p class="detail__message">
            <%= task.mobile.Mobile %>
          </p>
        </div>
        <div class="prototype__image">
            <%= image_tag task.image if task.image.attached? %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/tasks/edit.html.erb
<%= render "shared/header" %>
<%= render "tasks/form" %>

app/views/tasks/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Jumbotron example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/jumbotron/">

    

    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<main>
  <div class="container py-4">
    <%= render "shared/header" %>
    
    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>共有メモ</h2>
          <%= link_to "Add to", new_article_path, class: "text-decoration-none, btn btn-outline-secondary" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>キャンペーン</h2>
          <%= link_to "Add to", new_task_path, class: "text-decoration-none, btn btn-outline-secondary" %>
        </div>
      </div>
    </div>

    <%= form_with(url: search_tasks_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>

    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="calendar, w-100 p-3">
        <%= render partial: "tasks/calendar" %>
      </div>
    </div>
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">TEAM GOAL</h1>
        <%= render partial: "goals/goals-form" %>
      </div>

    <footer class="pt-3 mt-4 text-muted border-top">
      &copy; 2023
    </footer>
  </div>
</main>


    
  </body>
</html>

app/views/tasks/new.html.erb
<div class="container py-4">
  <%= render "shared/header" %>
  <%= render "tasks/form" %>
</div>

app/views/tasks/search.html.erb
<%= render "shared/header" %>

<%= form_with(url: search_tasks_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<div class="contents row">
  <% @tasks.each do |task| %>
    <!-- ここに検索結果のビュー -->
    <%= render partial: "task", locals: { task: task } %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<%= render "shared/header" %>

<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @task.title %>
      </p>
      <%# 投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <div class="prototype__manage">
          <% if user_signed_in? && current_user.id == @task.user_id %>
            <%= link_to "編集する", edit_task_path(@task), method: :get, class: :prototype__btn %>
            <%= link_to "削除する", task_path(@task), method: :delete, class: :prototype__btn %>
          <% end %>
            <%= link_to '戻る', root_path, class: :prototype__btn %>
        </div>
      <%# // 投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャンペーン内容</p>
          <p class="detail__message">
            <%= @task.content %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">携帯キャリア</p>
          <p class="detail__message">
            <%= @task.mobile.Mobile %>
          </p>
        </div>
        <div class="d-flex justify-content-center">
          <div class="tag">
            <% @task.tags.each do |tag| %>
              <span><%= tag.tag_name %></span>
            <% end %>
          </div>
        </div>
        <div class="prototype__image">
            <%= image_tag @task.image if @task.image.attached? %>
        </div>
      </div>
    </div>
  </div>
</main>