config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'tasks#index'
  resources :goals
  resources :articles
  resources :tasks do
    collection do
      get 'search'
    end
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user

  validates :goal_name, presence: true
  validates :goal_number, presence: true, numericality: { only_integer: true }
  validates :achievement_number, presence: true, numericality: { only_integer: true }
  
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @goals = Goal.all
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)

    @goal.save
    redirect_to root_path
  end

  private
  def goal_params
    params.require(:goal).permit(:goal_name, :goal_number , :achievement_number).merge(user_id: current_user.id)
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_goals-form.erb
<%= form_with(url: goals_path, method: :post, local: true, class: "goals-form") do |f| %>
  <table id="goals-table">
    <thead>
      <tr>
        <th>項目</th>
        <th>目標数</th>
        <th>獲得数</th>
        <th>達成率</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= f.text_field :'goal[goal_name]' %></td>
        <td><%= f.number_field :'goal[goal_number]' %></td>
        <td><%= f.number_field :'goal[achievement_number]' %></td>
        <td><span class="achievement-rate">0%</span></td>
      </tr>
    </tbody>
  </table>
  <button type="button" id="add-goal">項目を追加</button>
  <button type="submit" id="add-storage">保存</button>
<% end %>